export const catEatMembers: string[] = [
  "RoboCat",
  "laweaespacial",
  "Boos | Twitch",
  "tadeyon",
  "moth",
  "RojjzV | Twitch",
  "liftie",
  "HippoThicc | Twitch",
  "dank",
  "RedPandaXL | ttv?",
  "GDIAH",
  "Korean Boi",
  "763",
  "Xenology",
  "Mocrox",
  "jimbo15ow",
  "Icarus",
  "wherswallace",
  "uwuzi",
  "Fijxu",
  "Mel0n",
  "Aerozos",
  "storm",
  "Realities",
  "ttv/snooozn",
  "Yuri ♥",
  "FormerVectorEnjoyer",
  "Seabus",
  "887",
  "aost",
  "ciseru",
  "very retarted",
  "Tuhtter | Twitch",
  "Nyxie",
  "nyamu",
];
